# 这个起始工作流适用于在多个平台上运行的 CMake 项目。如果您只需要单个平台，有不同的起始工作流。
# 参见：https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # 将 fail-fast 设置为 false 以确保为所有矩阵组合提供反馈。当您的工作流稳定时，请考虑将其更改为 true。
      fail-fast: false

      # 设置矩阵以运行以下 3 种配置：
      # 1. <Windows, Release, 默认运行器镜像上的最新 MSVC 编译器工具链，默认生成器>
      # 2. <Linux, Release, 默认运行器镜像上的最新 GCC 编译器工具链，默认生成器>
      # 3. <Linux, Release, 默认运行器镜像上的最新 Clang 编译器工具链，默认生成器>
      #
      # 要添加更多构建类型（Release、Debug、RelWithDebInfo 等），请自定义 build_type 列表。
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      # 设置 Python 3.12 环境，用于构建过程中的依赖
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      # 安装 Python 依赖包（如果需要的话）
      run: |
        python -m pip install --upgrade pip
        # 如果有 requirements.txt 文件，取消下面一行的注释
        # pip install -r requirements.txt

    - name: Set reusable strings
      # 将重复的输入字符串（如构建输出目录）转换为步骤输出。这些步骤输出可以在整个工作流文件中使用。
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      # 在 'build' 子目录中配置 CMake。只有在使用单配置生成器（如 make）时才需要 `CMAKE_BUILD_TYPE`。
      # 参见 https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      # 使用给定配置构建您的程序。请注意，需要 --config 是因为默认的 Windows 生成器是多配置生成器（Visual Studio 生成器）。
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # 执行由 CMake 配置定义的测试。请注意，需要 --build-config 是因为默认的 Windows 生成器是多配置生成器（Visual Studio 生成器）。
      # 更多详细信息请参见 https://cmake.org/cmake/help/latest/manual/ctest.1.html
      run: ctest --build-config ${{ matrix.build_type }}

  # PyPI 发布作业 - 仅在构建成功且推送到 main 分支时运行
  pypi-publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      # 设置 Python 3.12 环境用于打包
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install build dependencies
      # 安装构建和打包所需的依赖
      run: |
        python -m pip install --upgrade pip
        pip install build wheel setuptools
    
    - name: Build Python package
      # 构建 Python 包分发文件
      run: |
        python -m build
    
    - name: Publish to PyPI
      # 发布到 PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        # PyPI 用户名（可选，默认为 __token__）
        user: __token__
        # PyPI 访问令牌（需要在 GitHub Secrets 中设置 PYPI_API_TOKEN）
        password: ${{ secrets.PYPI_API_TOKEN }}
        # 分发文件的目录（默认为 dist）
        packages-dir: dist
        # 上传前验证元数据
        verify-metadata: true
        # 如果包已存在则跳过（避免重复上传失败）
        skip-existing: false
        # 显示详细输出
        verbose: true
        # 显示文件哈希值
        print-hash: true
